services:
  - type: web
    name: backend
    runtime: image
    image:
      url: frappe/erpnext:v15.34.2
    envVars:
      - key: DB_HOST
        value: db
      - key: DB_PORT
        value: "3306"
      - key: REDIS_CACHE
        value: redis-cache:6379
      - key: REDIS_QUEUE
        value: redis-queue:6379
      - key: SOCKETIO_PORT
        value: "9000"

